[pytest]
log_cli = true
log_cli_level = INFO

log_cli_format = %(asctime)s [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)

log_cli_date_format = %Y-%m-%d %H:%M:%S

log_file = logs/pytest-logs.txt
log_file_level = DEBUG
log_file_format = %(asctime)s [%(levelname)s] %(message)s
markers =
    smoke: mark tests as smoke, only run in smoke testing phase
    regression: mark tests as regression, only run in regression testing phase
    ui: mark tests as UI (Selenium) tests
    api: mark tests as API (requests) tests
    crud: mark tests that exercise CRUD operations

addopts = --alluredir=reports/allure-results --clean-alluredir

testpaths =
    step_definitions
    tests_api
